# 1. Use the official Python image (use the version matching your mac)
FROM python:3.11-slim

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy your requirements file first (for faster builds)
COPY requirements.txt .

# 4. Install your python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copy the rest of your project code
COPY . .

# 6. Set the PYTHONPATH so your 'from storage.db' imports work
ENV PYTHONPATH=/app/src

# 7. The command to run your script
CMD ["python", "-m", "ingestion.fetch_news"]
# CMD ["python", "-m", "storage.init_db"]